### ISSUE TITLE
Filenames contained by the msg file ending with a whitespace will throw an error

### ISSUE THREAD

**Issue by Eleos91** [HiraokaHyperTools/msgreader#4]
If one of the filenames contained by the msg file ends with a whitespace, the msg file can not be extracted and throws one of two possible errors:
`TypeError: Cannot read property 'name' of undefined` or
`TypeError: Cannot read property 'split' of undefined`

**Comment by kenjiuno** [comment]
@Eleos91 Hi thanks for reporting this!
Is there any sample MSG containing the problematic filenames.
I want to reproduce it...

**Comment by kenjiuno** [comment]
Ok cygwin could make such a file in my Windows 10!

```sh
KU@H270 ~/trailing-space
$ touch "a.txt   "

KU@H270 ~/trailing-space
$ ls -l
合計 0
-rw-r--r-- 1 KU KU 0 5月  12 14:32 'a.txt   '
```

**Comment by kenjiuno** [comment]
I have made sample mails for repro: [trailing-space-eml-and-msg.zip](https://github.com/HiraokaHyperTools/msgreader/files/4613675/trailing-space-eml-and-msg.zip)

**Comment by kenjiuno** [comment]
> If one of the filenames contained by the msg file ends with a whitespace, the msg file can not be extracted and throws one of two possible errors:

What's the expected behavior on msgreader?

msgreader can extract attachment files having trailing space file name like `trailing-space.txt       ` on Windows 10.
However majority programs fail to access the file `trailing-space.txt       `.

In another side, Outlook 2013 seems to rename the not valid names forcefully by attaching `_` at trailing.

![2020-05-12_19h27_08](https://user-images.githubusercontent.com/5955540/81673500-b3b91080-9486-11ea-8833-cd5eb5c4faec.png)

This is the behavior you will expect on msgreader?

**Comment by Eleos91** [comment]
I can not share the samples (in total 48 samples) that can replicate the issue can't be shared because those .mgs files are sensitive data. The sample you provided actually doesn't throw an error... When I find some time, i will investigate those files a bit more and try to replicate the error with a self made .msg file i can share with you
