### ISSUE TITLE
Bug In this parser i didnot get html content of msg what should i do for this 

### ISSUE THREAD

**Issue by Anil890-bt** [HiraokaHyperTools/msgreader#45]
@HiraokaHyperTools @kenjiuno   solve this issue this parser didnot parse html it parse in unity8 numbers solve this

**Comment by kenjiuno** [comment]
You can try this demo site to determine whether HTML can be obtained from msg file or not.

https://hiraokahypertools.github.io/msgreader_demo3/

**Comment by Anil890-bt** [comment]
this code  were converted by rtf to html can parse directly with your package

**Comment by kenjiuno** [comment]
If msg file contains HTML body, `bodyHtml` property will be set. Otherwise it is not contained in msg file anymore. In other word, it has been lost when you received the message with Outlook or such mailer.

https://hiraokahypertools.github.io/msgreader/typedoc/interfaces/MsgReader.FieldsData.html#bodyHtml
